/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vectorOps_VectorMulJni */

#ifndef _Included_vectorOps_VectorMulJni
#define _Included_vectorOps_VectorMulJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vectorOps_VectorMulJni
 * Method:    mapVectorMul
 * Signature: (LvectorOps/VectorBean;)LvectorOps/VectorBean;
 */
JNIEXPORT jobject JNICALL Java_vectorOps_VectorMulJni_mapVectorMul
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
