/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_MapCopyFunc */

#ifndef _Included_test_MapCopyFunc
#define _Included_test_MapCopyFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_MapCopyFunc
 * Method:    arrayCopy
 * Signature: (Ltest/DoubleArray;)Ltest/DoubleArray;
 */
JNIEXPORT jobject JNICALL Java_test_MapCopyFunc_arrayCopy
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
