/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pairHMM_LoadSizesJniFunction */

#ifndef _Included_pairHMM_LoadSizesJniFunction
#define _Included_pairHMM_LoadSizesJniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pairHMM_LoadSizesJniFunction
 * Method:    loadSizes
 * Signature: (LpairHMM/SizesBean;)LpairHMM/WorkloadPairHmmBean;
 */
JNIEXPORT jobject JNICALL Java_pairHMM_LoadSizesJniFunction_loadSizes
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
