/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pairHMM_PairHmmJniFunction */

#ifndef _Included_pairHMM_PairHmmJniFunction
#define _Included_pairHMM_PairHmmJniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pairHMM_PairHmmJniFunction
 * Method:    calculateSoftware
 * Signature: (LpairHMM/PairHmmBean;)LpairHMM/PairHmmBean;
 */
JNIEXPORT jobject JNICALL Java_pairHMM_PairHmmJniFunction_calculateSoftware
  (JNIEnv *, jobject, jobject);

/*
 * Class:     pairHMM_PairHmmJniFunction
 * Method:    calculateHardware
 * Signature: (LpairHMM/PairHmmBean;)LpairHMM/PairHmmBean;
 */
JNIEXPORT jobject JNICALL Java_pairHMM_PairHmmJniFunction_calculateHardware
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
