/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pairHMM_DataLoaderJniFunction */

#ifndef _Included_pairHMM_DataLoaderJniFunction
#define _Included_pairHMM_DataLoaderJniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pairHMM_DataLoaderJniFunction
 * Method:    callDataLoader
 * Signature: (LpairHMM/WorkloadPairHmmBean;)LpairHMM/ByteArrBean;
 */
JNIEXPORT jobject JNICALL Java_pairHMM_DataLoaderJniFunction_callDataLoader
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
