/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tudelft_ewi_ceng_examples_pairHMM_LoadSizesJniFunction */

#ifndef _Included_org_tudelft_ewi_ceng_examples_pairHMM_LoadSizesJniFunction
#define _Included_org_tudelft_ewi_ceng_examples_pairHMM_LoadSizesJniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tudelft_ewi_ceng_examples_pairHMM_LoadSizesJniFunction
 * Method:    loadSizes
 * Signature: (Lorg/tudelft/ewi/ceng/examples/pairHMM/SizesBean;)Lorg/tudelft/ewi/ceng/examples/pairHMM/WorkloadPairHmmBean;
 */
JNIEXPORT jobject JNICALL Java_org_tudelft_ewi_ceng_examples_pairHMM_LoadSizesJniFunction_loadSizes
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
