/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tudelft_ewi_ceng_examples_pairHMM_DataLoaderJniFunction */

#ifndef _Included_org_tudelft_ewi_ceng_examples_pairHMM_DataLoaderJniFunction
#define _Included_org_tudelft_ewi_ceng_examples_pairHMM_DataLoaderJniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tudelft_ewi_ceng_examples_pairHMM_DataLoaderJniFunction
 * Method:    callDataLoader
 * Signature: (Lorg/tudelft/ewi/ceng/examples/pairHMM/WorkloadPairHmmBean;)Lorg/tudelft/ewi/ceng/examples/pairHMM/ByteArrBean;
 */
JNIEXPORT jobject JNICALL Java_org_tudelft_ewi_ceng_examples_pairHMM_DataLoaderJniFunction_callDataLoader
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
