/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tudelft_ewi_ceng_examples_pairHMM_PairHmmJniFunction */

#ifndef _Included_org_tudelft_ewi_ceng_examples_pairHMM_PairHmmJniFunction
#define _Included_org_tudelft_ewi_ceng_examples_pairHMM_PairHmmJniFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tudelft_ewi_ceng_examples_pairHMM_PairHmmJniFunction
 * Method:    calculateSoftware
 * Signature: (Lorg/tudelft/ewi/ceng/examples/pairHMM/PairHmmBean;)Lorg/tudelft/ewi/ceng/examples/pairHMM/PairHmmJniFunction;
 */
JNIEXPORT jobject JNICALL Java_org_tudelft_ewi_ceng_examples_pairHMM_PairHmmJniFunction_calculateSoftware
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_tudelft_ewi_ceng_examples_pairHMM_PairHmmJniFunction
 * Method:    calculateHardware
 * Signature: (Lorg/tudelft/ewi/ceng/examples/pairHMM/PairHmmBean;)Lorg/tudelft/ewi/ceng/examples/pairHMM/PairHmmJniFunction;
 */
JNIEXPORT jobject JNICALL Java_org_tudelft_ewi_ceng_examples_pairHMM_PairHmmJniFunction_calculateHardware
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
