/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_heterojni_examples_vectorOps_VectorAddJni */

#ifndef _Included_org_heterojni_examples_vectorOps_VectorAddJni
#define _Included_org_heterojni_examples_vectorOps_VectorAddJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_heterojni_examples_vectorOps_VectorAddJni
 * Method:    reduceVectorAdd
 * Signature: (Lorg/heterojni/examples/vectorOps/VectorBean;Lorg/heterojni/examples/vectorOps/VectorBean;)Lorg/heterojni/examples/vectorOps/VectorBean;
 */
JNIEXPORT jobject JNICALL Java_org_heterojni_examples_vectorOps_VectorAddJni_reduceVectorAdd
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
