/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_heterojni_examples_sparkJNIPi_RandOpenclPiMap */

#ifndef _Included_org_heterojni_examples_sparkJNIPi_RandOpenclPiMap
#define _Included_org_heterojni_examples_sparkJNIPi_RandOpenclPiMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_heterojni_examples_sparkJNIPi_RandOpenclPiMap
 * Method:    randToSum
 * Signature: (Lorg/heterojni/examples/sparkJNIPi/PiBean;)Lorg/heterojni/examples/sparkJNIPi/PiBean;
 */
JNIEXPORT jobject JNICALL Java_org_heterojni_examples_sparkJNIPi_RandOpenclPiMap_randToSum
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
