/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vectorOps_VectorAddJni */

#ifndef _Included_vectorOps_VectorAddJni
#define _Included_vectorOps_VectorAddJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vectorOps_VectorAddJni
 * Method:    reduceVectorAdd
 * Signature: (LvectorOps/VectorBean;LvectorOps/VectorBean;)LvectorOps/VectorBean;
 */
JNIEXPORT jobject JNICALL Java_vectorOps_VectorAddJni_reduceVectorAdd
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
