/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tudelft_ceng_examples_vectorOps_VectorMulJni */

#ifndef _Included_org_tudelft_ceng_examples_vectorOps_VectorMulJni
#define _Included_org_tudelft_ceng_examples_vectorOps_VectorMulJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tudelft_ceng_examples_vectorOps_VectorMulJni
 * Method:    mapVectorMul
 * Signature: (Lorg/tudelft/ceng/examples/vectorOps/VectorBean;)Lorg/tudelft/ceng/examples/vectorOps/VectorBean;
 */
JNIEXPORT jobject JNICALL Java_org_tudelft_ceng_examples_vectorOps_VectorMulJni_mapVectorMul
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
